### ISSUE TITLE
L.Mixin.Events deprecation

### ISSUE THREAD

**Issue by A1rPun** [teastman/Leaflet.pattern#16]
Since Leaflet `v1.1.0` you get this [warning](https://github.com/Leaflet/Leaflet/commit/f010f5829476bee63814ec3d57f180c853e2a6ce):
> Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. undefined

**Comment by Mweydert** [comment]
#https://github.com/A1rPun/Leaflet.pattern/commit/89d9545d5fa8c9ed9db8b1740dee0637ba5f180f also needed. 
Thanks for the fix.
