### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by IvanSanchez** [teastman/Leaflet.pattern#4]
As requested in Leaflet/Leaflet#2214, please add a demo webpage to showcase the plugin.

**Comment by pgiraud** [comment]
Using `gh-pages` may help.

**Comment by teastman** [comment]
Added demo examples via gh-pages https://github.com/teastman/Leaflet.pattern/commit/6898228b78fa10e5cdb1c57ce7322980fe5f8401
