### ISSUE TITLE
Geojson pattern doesn't work

### ISSUE THREAD

**Issue by truongndnnguyen** [teastman/Leaflet.pattern#7]
I don't know how to make this work with geojson. I assume just need to pass fillPattern in geojson option like below

L.geoJson(geojson, {fillPattern: this.stripes}).addTo(this.map)

Please confirm this plugin work in this case

**Comment by teastman** [comment]
L.geoJson(geojson, {style: {fillPattern: this.stripes}}).addTo(this.map)
